version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.10"
  jobs:
    pre_build:
      - rm -f docs/multibase.rst docs/modules.rst
      - python -m sphinx.ext.apidoc -o docs/ multibase

sphinx:
  configuration: docs/conf.py
  fail_on_warning: true

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - dev

formats:
  - epub
  - htmlzip
